from coremis_app_integration.endpoints.login import login
from coremis_app_integration.endpoints.change_password import change_password
from coremis_app_integration.endpoints.payment_details import payment_details
